name: Semgrep

on:
  pull_request: {}
  push:
    branches: ["main", "master"]
  schedule:
    - cron: '20 17 * * *'  # daily, change to a random time

permissions:
  contents: read
  security-events: write  # required to upload SARIF to GitHub Security tab

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Semgrep
        run: semgrep scan --config auto --sarif > semgrep.sarif
      - name: Upload to GitHub Security tab
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: semgrep.sarif
        if: always()
